version: 0.0
os: linux

files:
  - source: /dist
    destination: /home/ec2-user/event-monitor/dist
  - source: /scripts
    destination: /home/ec2-user/event-monitor/scripts
  - source: /package.json
    destination: /home/ec2-user/event-monitor
  - source: /pnpm-lock.yaml
    destination: /home/ec2-user/event-monitor

permissions:
  - object: /home/ec2-user/event-monitor
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - file
      - directory

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_application.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 300
      runas: root 