version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm install --production=false
      - npm install -g typescript  # Ensure TypeScript is available globally

  pre_build:
    commands:
      - echo "Starting pre-build phase..."
      - echo "Cleaning any existing dist directory..."
      - rm -rf dist/

  build:
    commands:
      - echo "Starting build phase..."
      - npm run build
      - echo "Build completed"

  post_build:
    commands:
      - echo "Starting post-build phase..."
      - echo "Copying files to deployment directory..."
      - mkdir -p deployment
      - cp -r dist src package.json package-lock.json tsconfig.json scripts appspec.yml deployment/
      - echo "Build completed on `date`"

artifacts:
  files:
    - '**/*'
  base-directory: 'deployment'
  discard-paths: false

cache:
  paths:
    - 'node_modules/**/*'