version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install -g pnpm
      - pnpm install --no-frozen-lockfile

  build:
    commands:
      - echo "Starting build phase..."
      - pnpm build
      - echo "Build completed"

  post_build:
    commands:
      - echo "Starting post-build phase..."
      - echo "Build completed on `date`"

artifacts:
  files:
    - appspec.yml
    - scripts/**/*
    - dist/**/*
    - package.json
    - pnpm-lock.yaml
    - tsconfig.json
  exclude-paths:
    - node_modules/**/*
    - .pnpm-store/**/*
    - .git/**/*
    - .env*
    - config/**/*
    - "*.md"
  base-directory: '.'
  discard-paths: false

cache:
  paths:
    - 'node_modules/**/*'
    - '.pnpm-store/**/*'