version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install -g pnpm
      - pnpm install --no-frozen-lockfile

  build:
    commands:
      - echo "Starting build phase..."
      - pnpm build
      - echo "Build completed, setting up deployment structure..."
      - mkdir -p dist/scripts
      - cp -r scripts/* dist/scripts/
      - echo "Copied scripts to dist/scripts/"

  post_build:
    commands:
      - echo "Starting post-build phase..."
      - pwd
      - ls -la
      # Create the deployment package
      - echo "Creating deployment package..."
      # First, create the zip file with appspec.yml at the root
      - zip -r event-monitor.zip appspec.yml
      # Then add the rest of the files
      - cd dist
      - zip -r ../event-monitor.zip .
      - cd ..
      - echo "Created deployment archive"
      - echo "Verifying archive contents:"
      - unzip -l event-monitor.zip

artifacts:
  files:
    - event-monitor.zip
  discard-paths: no

cache:
  paths:
    - 'node_modules/**/*'
    - '.pnpm-store/**/*' 