version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install -g pnpm
      - cd src/ec2-event-monitor
      - pnpm install

  build:
    commands:
      - pnpm build
      - cp appspec.yml dist/
      - cp scripts/* dist/scripts/
      - cp event-monitor.service dist/

  post_build:
    commands:
      - cd dist
      - zip -r ../event-monitor.zip .

artifacts:
  files:
    - event-monitor.zip
  discard-paths: yes

cache:
  paths:
    - 'node_modules/**/*'
    - '.pnpm-store/**/*' 