version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install -g pnpm
      - pnpm install --no-frozen-lockfile
  
  pre_build:
    commands:
      - echo "Starting pre-build phase"
      - aws --version
  
  build:
    commands:
      - echo "Starting build phase"
      - pnpm run build
      - ls -la dist/
      
  post_build:
    commands:
      - echo "Starting post-build phase"
      - cp package.json dist/
      - cp pnpm-lock.yaml dist/
      - cd dist && pnpm install --prod --no-frozen-lockfile
      - ls -la

artifacts:
  base-directory: .
  files:
    - dist/**/*
    - scripts/**/*
    - appspec.yml
    - package.json
    - pnpm-lock.yaml
  discard-paths: false

cache:
  paths:
    - 'node_modules/**/*'
    - '.pnpm-store/**/*' 