version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install -g pnpm
      - pnpm install --no-frozen-lockfile

  build:
    commands:
      - pnpm build
      - cp appspec.yml dist/
      - mkdir -p dist/scripts
      - cp -r scripts/* dist/scripts/

  post_build:
    commands:
      - cd dist
      - zip -r ../event-monitor.zip .

artifacts:
  files:
    - event-monitor.zip
  discard-paths: yes

cache:
  paths:
    - 'node_modules/**/*'
    - '.pnpm-store/**/*' 