version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm install --production=false

  build:
    commands:
      - echo "Starting build phase..."
      - npm run build
      - echo "Build completed"

  post_build:
    commands:
      - echo "Starting post-build phase..."
      - echo "Build completed on `date`"

artifacts:
  files:
    - appspec.yml
    - scripts/**/*
    - src/**/*
    - dist/**/*
    - package.json
    - package-lock.json
    - tsconfig.json
  exclude-paths:
    - node_modules/**/*
    - .git/**/*
    - .env*
    - config/**/*
    - "*.md"
  base-directory: '.'
  discard-paths: false

cache:
  paths:
    - 'node_modules/**/*'