version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install -g pnpm
      - pnpm install --no-frozen-lockfile

  build:
    commands:
      - echo "Starting build phase..."
      - pnpm build
      - echo "Build completed"

  post_build:
    commands:
      - echo "Starting post-build phase..."
      # Create a clean deployment directory
      - rm -rf deployment
      - mkdir -p deployment
      # Copy appspec.yml to root of deployment
      - cp appspec.yml deployment/
      # Create application directory structure
      - mkdir -p deployment/scripts
      - cp -r scripts/* deployment/scripts/
      # Ensure scripts are executable
      - chmod +x deployment/scripts/*.sh
      - cp -r dist/* deployment/
      # Verify deployment structure
      - echo "Deployment directory structure:"
      - ls -la deployment/
      - echo "Scripts directory:"
      - ls -la deployment/scripts/
      # Create deployment archive
      - cd deployment
      - zip -r ../event-monitor.zip .
      - cd ..
      # Verify archive contents and permissions
      - echo "Archive contents:"
      - unzip -l event-monitor.zip
      - echo "Checking for appspec.yml:"
      - unzip -l event-monitor.zip | grep appspec.yml
      - echo "Checking script permissions:"
      - unzip -l event-monitor.zip | grep "\.sh"

artifacts:
  files:
    - event-monitor.zip
  discard-paths: no

cache:
  paths:
    - 'node_modules/**/*'
    - '.pnpm-store/**/*' 