version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install -g pnpm
      - pnpm install --no-frozen-lockfile

  build:
    commands:
      - echo "Starting build phase..."
      - pnpm build
      - echo "Build completed"

  post_build:
    commands:
      - echo "Starting post-build phase..."
      # Debug current location
      - pwd
      - echo "Listing current directory:"
      - ls -la
      # Create deployment package directly
      - zip -r event-monitor.zip appspec.yml scripts/* dist/*
      # Verify the contents
      - echo "Verifying archive contents:"
      - unzip -l event-monitor.zip
      - echo "Checking for appspec.yml:"
      - unzip -l event-monitor.zip | grep -i "appspec.yml"

artifacts:
  files:
    - event-monitor.zip
  discard-paths: no

cache:
  paths:
    - 'node_modules/**/*'
    - '.pnpm-store/**/*' 